# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65570d86d959b744c120d8457e1b379fbdefb59e70487d70d89caa43e5ced8a308a1c5acd7145e53925940bd5c1e55545be8b30b7dee6b1868b6b83e5d2c9ad

test:
  secret_key_base: c96d136db18f771613835f919c8c00b9a79403e1edf441f2b5fcf59a8a9a79bf60af0238b2ff41485b520ce0a1ba129c3f6fe734e09e621d7bd15e667a92dde5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
